name: Document checks

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Test document checker
        run: python3 scripts/test_check_docs.py
      - name: Check documents
        run: python3 scripts/check_docs.py
